### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by thongtrinh2204** [mebjas/CSRF-Protector-PHP#128]
How can i remove this warning meesage?
`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience`
![image](https://user-images.githubusercontent.com/9380494/82417913-79fb9180-9aa6-11ea-9014-510c16096d3d.png)

**Comment by mebjas** [comment]
Thanks for reporting I'll try to repro and fix thi.

**Comment by mebjas** [comment]
So the reason you see this issue is because CSRF Protector javascript library adds an interceptor to all Ajax calls to attach a CSRF Token. **But it doesn't change the properties of the call - if the underlying ajax call (XMLHttpRequest) call was made without async = true - you'd get this warning.**

If it's set to true, then CSRF Protector will also set it to true - https://github.com/mebjas/CSRF-Protector-PHP/blob/master/js/csrfprotector.js#L279 is where it's done.


So **TL;DR;** **this is not the library's fault the caller must be doing making sync call which is now deprecated by the browser.**

From the stack trace it looks like you are using `jQuery` to make the `AJAX` call. Latest version by default makes async call - please check if you are using latest jQuery or are explicitly making `async:false` in `$.ajax` - https://api.jquery.com/jquery.ajax/

**Comment by mebjas** [comment]
I am closing this as this is not a bug in library - but open to following up more on how to fix this issue from your side.

**Comment by thongtrinh2204** [comment]
@mebjas thank you for pointing this out, I have some ajax calls with async = false in my application and now I know how to remove this warning,

**Comment by mebjas** [comment]
No worries!
