### ISSUE TITLE
Questions about the installation

### ISSUE THREAD

**Issue by elieobeid7** [mebjas/CSRF-Protector-PHP#85]
I installed it via composer. it says

> For composer installations: Copy the config.sample.php file into your root folder at config/csrf_config.php

So Ok I would need to copy that to the root folder of my app, is that all? My questions are

- Why would I need to do that? Why wouldn't just get installed via composer like all other libraries

- Why would I need to do

`include_once __DIR__ .'/vendor/owasp/csrf-protector-php/libs/csrf/csrfprotector.php';`

Shouldn't that be done automatically via composer?

- What's jsPath and Jsurl? all js files handling ajax requests? or are they libraries that comes with this repo?

**Comment by mebjas** [comment]
Answers:
### Why would you need to do that: 
Well there are some parameters in the config file which need to be tweaked before the library can be used - `jsurl` primarily. So to ensure that - the config file is provided as `config.sample.php` rather than `config.php`. Irrespective of you having installed using composer or not, you can keep the config file where it is. Keeping in the root folder just works in sync with the composer style. 

### Why wouldn't just get installed via composer like all other libraries?
I don't know of automated way to ensure the file is copied during composer installation to required directory. Again since some manual effort is needed to configure the solution, it's better to do the copying. It ensures the necessary step is taken. 

### Why do you need to include the script everywhere
The library works as an interceptor; Hence you need to include the module once before using it.

### `jsPath` & `jsUrl`
`jsPath` is absolute path of js code provided with the library. It's gonna be obsolete pretty soon. `jsUrl` is the url of the same js script accessible from web clients to user. The library buffers the output and appends this code to the `HTML` one. This script running on client side takes care of rest of stuff.

p.s I'm not an expert with composer so any contribution is welcome.

**Comment by mebjas** [comment]
@elieobeid7 - let me know if you have more questions, else I'll close this issue.

**Comment by elieobeid7** [comment]
```
<?php
/**
 * Configuration file for CSRF Protector
 * Necessary configurations are (library would throw exception otherwise)
 * ---- logDirectory
 * ---- failedAuthAction
 * ---- jsUrl
 * ---- tokenLength

 */
return array(
	"CSRFP_TOKEN" => "",
	"logDirectory" => "../log",
	"failedAuthAction" => array(
		"GET" => 0,
		"POST" => 0),
	"errorRedirectionPage" => "",
	"customErrorMessage" => "",
	"jsUrl" => "https://example.com/common/vendor/owasp/csrf-protector-php/csrfprotector.js",
	"tokenLength" => 10,
	"cookieConfig" => array(
		"path" => 'common/vendor/owasp/csrf-protector-php/libs/csrf/csrfprotector.php',
		"domain" => 'example.com',
		"secure" => true
	),
	"disabledJavascriptMessage" => "This site attempts to protect users against <a href=\"https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29\">
	Cross-Site Request Forgeries </a> attacks. In order to do so, you must have JavaScript enabled in your web browser otherwise this site will fail to work correctly for you.
	 See details of your web browser for how to enable JavaScript.",
	 "verifyGetFor" => array()
);
```

Installed through composer, latest version, the relative path is the one that's causing the problem.

**Comment by elieobeid7** [comment]
I fixed the problem, the readme said

> For composer installations: Copy the config.sample.php file into your root folder at config/csrf_config.php

But in fact we don't have to place it anywhere, we just have to rename it to config.php and leave it where it is. Then the config becomes like so

```
$token = $_SESSION['token']; 
return array(
	"CSRFP_TOKEN" => $token,
	"logDirectory" => "../log",
	"failedAuthAction" => array(
		"GET" => 0,
		"POST" => 0),
	"errorRedirectionPage" => "",
	"customErrorMessage" => "",
	"jsUrl" => "https://example.com/common/vendor/owasp/csrf-protector-php/csrfprotector.js",
	"tokenLength" => 10,
	"cookieConfig" => array(
		"path" => 'csrf/csrfprotector.php',
		"domain" => 'example.com',
		"secure" => true
	),
	"disabledJavascriptMessage" => "This site attempts to protect users against <a href=\"https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29\">
	Cross-Site Request Forgeries </a> attacks. In order to do so, you must have JavaScript enabled in your web browser otherwise this site will fail to work correctly for you.
	 See details of your web browser for how to enable JavaScript.",
	 "verifyGetFor" => array()
);
```
Maybe it's a typing mistake, maybe I misunderstood, in any case this is awesome library, thank you
